# Generated by Django 4.0.4 on 2022-05-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_floor_parent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='parent_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.location'),
        ),
    ]
