# Generated by Django 4.0.4 on 2022-05-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_booking', models.DateField()),
                ('end_booking', models.DateField()),
                ('parent_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.desk')),
            ],
        ),
    ]
